include:
  - proxy.yaml

services:
  web:
    image: cr.yandex/crp44di9pfims0uojh6k/custom-web:1.0.0
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.5
    env_file:
      - /home/makaron/.env
    environment:
      MYSQL_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  db:
    image: mysql:8
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.10
    env_file:
      - /home/makaron/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24